version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    command: sh start_project.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=myproject.settings

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    command: celery -A myproject worker --loglevel=info --pool=solo
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_beat
    command: celery -A myproject beat --loglevel=info
    depends_on:
      - redis
    volumes:
      - ./celerybeat-schedule.db:/app/celerybeat-schedule.db
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
